name: food_waste
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  cloud_firestore: ^2.4.0
  firebase_core: ^1.4.0
  firebase_storage: ^10.0.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  image_picker: ^0.8.3
  location: ^4.2.0

flutter:
  uses-material-design: true
